name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # ou a branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Instalar pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # Build do projeto
      - name: Build
        run: pnpm run build

      # Deploy para GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # ou pasta de build do seu projeto
